from tkinter import *
class Vegetables:
	def letter(self,m):
		tmp = var1.get(m)
		rate = rate.get(tmp)
		result.set(rate)
		def weight(self,kgs):
			cost = kgs*rate
			return cost
d = {'Carrot':'12.5','Onion':'21','Radish':'12','Drumstick':'22','Ladies Finger':'30','Beans':'18','Capcisum':'22','Potato':'32'}
obj = Tk()
obj1 = Vegetables()
obj.geometry('630x160')
obj.title('Vegetable shop')
lab1 = Label(obj,text="Item:")
lab1.place(x=20,y=10)
lab2 = Label(obj,text="Rate:")
lab2.place(x=195,y=10)
lab3 = Label(obj,text="Weight:")
lab3.place(x=365,y=10)
lab4 = Label(obj,text="Cost:")
lab4.place(x=200,y=40)
var1 = StringVar()
var2 = StringVar()
result = StringVar()
item_box = Entry(obj,textvariable = var1)
item_box.place(x=57, y = 10)
item_rate = Entry(obj,textvariable = var2)
item_rate.place(x=230,y=10)
item_weight = Entry(obj,textvariable = var2)
item_weight.place(x=415,y=10)
item_result = Entry(obj,textvariable = result)
item_result.place(x=250,y=40)
carrot = Button(obj,text = 'Carrot', bg = 'orange', fg = 'black', bd = '10', command = obj1.letter(m))
carrot.place (x=15,y=80)
beans = Button(obj,text = 'beans', bg = 'sky blue', fg = 'black', bd = '10', command = obj1.letter(m))
beans.place (x=80,y=80)
radish = Button(obj,text = 'Radish', bg = 'grey', fg = 'black', bd = '10', command = obj1.letter(m))
radish.place (x=145,y=80)
drumstick = Button(obj,text = 'Drumstick', bg = 'light green', fg = 'black', bd = '10', command = obj1.letter(m))
drumstick.place (x=212,y=80)
capsicum = Button(obj,text = 'Capsicum', bg = 'green', fg = 'black', bd = '10', command = obj1.letter(m))
capsicum.place (x=300,y=80)
onion = Button(obj,text = 'Onion', bg = 'pink', fg = 'black', bd = '10', command = obj1.letter(m))
onion.place (x=385,y=80)
ladies_finger = Button(obj,text = 'Ladies Finger', bg = 'yellow', fg = 'black', bd = '10', command = obj1.letter(m))
ladies_finger.place (x=450,y=80)
potato = Button(obj,text = 'Potato', bg = 'light yellow', fg = 'black', bd = '10', command = obj1.letter(m))
potato.place (x=550,y=80)
obj.mainloop()